[build]
  command = "ng build"
  # CORRECCIÓN: Apuntamos directamente a la carpeta /browser como pidió Netlify
  publish = "dist/mini-tech-angular/browser"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200